export { default as Slack } from './Slack.svg'
export { default as Amazon } from './Amazon.svg'
export { default as Woo } from './Woo.svg'
export { default as MeUndies } from './MeUndies.svg'
export { default as SitePoint } from './SitePoint.svg'
export { default as AirWallex } from './air-wallex.svg'
export { default as Ghost } from './ghost.svg'
export { default as HubSpot } from './hub-spot.svg'
export { default as Gusto } from './gusto.svg'
export { default as UpWork } from './upwork.svg'

export { default as AmazonColor } from './amazon-color.svg'
export { default as ContentfulColor } from './contentful-color.svg'
export { default as WhatsAppColor } from './whatsApp-color.svg'
export { default as DropboxColor } from './dropbox-color.svg'
export { default as SlackColor } from './slack-color.svg'
export { default as GGColor } from './gg-color.svg'
export { default as HubSpotColor } from './hubspot-color.svg'
export { default as GustoColor } from './gusto-color.svg'

